# Generated by Django 5.0.1 on 2024-01-27 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='model_file',
            field=models.FileField(upload_to='files/3d_models', verbose_name='Файл с моделью'),
        ),
        migrations.AlterField(
            model_name='room',
            name='photo_file',
            field=models.ImageField(upload_to='files/images', verbose_name='Фото плана проекта'),
        ),
    ]
